PACKAGE = rice.pastry.rmi

SOURCE  = \
	RMINodeHandle.java\
	RMIPastryNode.java\
	RMIPastryNodeFactory.java\
	RMIPastryNodeImpl.java\
	RMIPastrySecurityManager.java

RMI_SOURCE = RMIPastryNodeImpl.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
