PACKAGE = rice.pastry.control

SOURCE  = \
	SendOptions.java\
	Request.java\
	RequestGranted.java\
	RequestDenied.java\
	RequestJoin.java\
	RequestHandle.java\
	RequestLeafSet.java\
	RequestNeighbourSet.java\
	RequestRoutingTable.java\
	RouteMessage.java\
	RouterAddress.java\
	NodeArrived.java\
	NodeDown.java\
	UpdatedSince.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
