PACKAGE = rice.pastry.wire

SOURCE  = \
	DatagramManager.java\
	DatagramTransmissionManager.java\
	GlobalSocketManager.java\
	NeedsWakeUp.java\
	PendingWrite.java\
	SelectionKeyHandler.java\
	SelectorManager.java\
	SocketChannelReader.java\
	SocketChannelWriter.java\
	SocketManager.java\
	StaleSKH.java\
	Wire.java\
	WireLimitatioinListener.java\
	WireNodeHandle.java\
	WireNodeHandlePool.java\
	WirePastryNode.java\
	WirePastryNodeFactory.java\
	WirePastrySecurityManager.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
