PACKAGE = rice.pastry.wire

SOURCE  = \
	WirePastryNode.java\
	WirePastryNodeFactory.java\
	WirePastrySecurityManager.java\
	WireNodeHandle.java\
	WireNodeHandlePool.java\
	SelectorManager.java\
	SelectionKeyHandler.java\
	DatagramManager.java\
	DatagramTransmissionManager.java\
	SocketManager.java\
	SocketChannelReader.java\
	SocketChannelWriter.java\
	PendingWrite.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
