PACKAGE = rice.splitstream

SOURCE  = \
	Channel.java \
	ChannelId.java \
	SplitStreamImpl.java \
	ISplitStream.java \
	ISplitStreamApp.java \
	Stripe.java \
	StripeId.java\
	SpareCapacityId.java \
	SplitStreamOutputStream.java\
	BandwidthManager.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
