PACKAGE = rice.splitstream

SOURCE  = \
	Channel.java \
	ChannelId.java \
	SplitStreamImpl.java \
	ISplitStream.java \
	Stripe.java \
	StripeId.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
