PACKAGE = rice.pastry.wire.exception

SOURCE  = \
	DeserializationException.java \
	ImproperlyFormattedMessageException.java \
	NodeIsDeadException.java \
	SerializationException.java 

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
