PACKAGE = rice.splitstream.messaging

SOURCE  = \
	ControlAttachResponseMessage.java\
	ControlAttachMessage.java\
	SplitStreamAddress.java\
	ControlFindParentResponseMessage.java\
	ControlDropMessage.java\
	ControlPropogatePathMessage.java\
	ControlFindParentMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
