PACKAGE = rice.splitstream.messaging

SOURCE  = \
	ControlAttachResponseMessage.java\
	ControlAttachMessage.java
	#ControlDropMessage.java \
	#ControlMessage.java \
	#SplitStreamMessage.java \
      	#StripeContentMessage.java
#	ControlFindParentMessage.java \
	#ControlAddMessage.java \

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
