PACKAGE = rice.pastry.testing

SOURCE  = \
	NodeIdUnit.java\
	DummyNodeHandle.java\
	PastryTest.java\
	RMIPastryTest.java\
	PastryRegrTest.java\
	RegrTestApp.java

	#RoutingTableUnit.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
