PACKAGE = rice.p2p.replication.manager

SOURCE  = \
	ReplicationManager.java\
	ReplicationManagerClient.java\
	ReplicationManagerImpl.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
