PACKAGE = rice.p2p.scribe.messaging

SOURCE  = \
	ScribeMessage.java \
  AnycastMessage.java \
  PublishMessage.java \
  SubscribeMessage.java \
  UnsubscribeMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
