PACKAGE = rice.p2p.past.messaging

SOURCE  = \
  PastMessage.java \
  ContinuationMessage.java \
  InsertMessage.java \
  LookupMessage.java \
  FetchMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
