PACKAGE = rice.email.proxy.mailbox.postbox

SOURCE  = \
  PostFolder.java \
  PostMailbox.java \
  PostMailboxManager.java \
  PostFlagList.java \
  PostMessage.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
