PACKAGE = rice.pastry

SOURCE  = \
	NodeId.java\
	NodeIdFactory.java\
	NodeHandle.java\
	PastryNode.java\
	PastryNodeFactory.java\
	NodeSet.java\
	NodeSetUpdate.java \
	Log.java

#	NodeIdI.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
