PACKAGE = rice.p2p.commonapi

SOURCE  = \
	Application.java\
	Id.java\
	IdRange.java\
	IdFactory.java\
	Message.java\
	Node.java\
	NodeHandle.java\
	NodeHandleSet.java\
	RouteMessage.java\
	Endpoint.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

