PACKAGE = rice.pastry.rmi

SOURCE  = \
	RMIPastryNode.java\
	RMIRemoteNodeI.java\
	RMINodeHandle.java\
	RMINodeHandlePool.java\
	RMIPastryNodeFactory.java\
	RMIPastrySecurityManager.java

RMI_SOURCE = RMIPastryNode.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
