PACKAGE = rice.email.proxy.mailbox.filebox

SOURCE  = \
  FileFolder.java \
  FileMailbox.java \
  FileMailboxManager.java \
  FileFlagList.java \
  FileMessage.java \
  FileMessageList.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
