PACKAGE = rice.email.proxy.mail

SOURCE  = \
  MailAddress.java \
  MailException.java \
  MalformedAddressException.java \
  MimeMessage.java \
  MovingMessage.java \
  StoredMessage.java \
  MailDataHandler.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
