PACKAGE = rice.pastry.socket

SOURCE  = \
	SelectionKeyHandler.java\
	SelectorManager.java \
	SocketChannelReader.java \
	SocketChannelWriter.java\
	SocketCollectionManager.java\
	SocketNodeHandle.java\
	SocketNodeHandlePool.java\
	SocketPastryNode.java\
	SocketPastryNodeFactory.java\
	SocketPastrySecurityManager.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
