PACKAGE = rice.pastry.socket

SOURCE  = \
	SocketManager.java\
	SocketNodeHandle.java\
	SocketNodeHandlePool.java\
	SocketPastryNode.java\
	SocketPastryNodeFactory.java\
	SocketPastrySecurityManager.java\
	SocketManager.java\
	SocketChannelReader.java\
	SocketChannelWriter.java\
	SocketPingManager.java\
	SocketPingManagerAddress.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
