PACKAGE = rice.pastry.routing

SOURCE  = \
	RouteSet.java\
	RoutingTable.java\
	RouterAddress.java\
	SendOptions.java\
	RouteMessage.java\
	BroadcastRouteRow.java\
	RequestRouteRow.java\
	RouteProtocolAddress.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
