PACKAGE = rice.pastry.multiring.messaging

SOURCE	= \
	MultiRingApplAddress.java\
  MultiRingApplMessage.java\
  RingForwardMessage.java\
  RingIdRequestMessage.java\
  RingIdResponseMessage.java\
  RingLookupRequestMessage.java\
  RingLookupResponseMessage.java\
  RingLookupReminderMessage.java\

MAIN	= 

include $(JAVA_DEV_ROOT)/Makefile
