PACKAGE = rice.post

SOURCE  = \
	Post.java \
	PostClient.java \
	PostClientAddress.java \
	PostData.java \
	PostDataReference.java \
	PostException.java \
	PostEntityAddress.java \
	PostGroupAddress.java \
	PostUserAddress.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
