PACKAGE = rice.email.proxy.imap.commands

SOURCE  = \
  	AbstractImapCommand.java	 \
  	AppendCommand.java	 \
  	BadSyntaxCommand.java	 \
  	CapabilityCommand.java	 \
  	CheckCommand.java	 \
  	CloseCommand.java	 \
  	CopyCommand.java	 \
  	CreateCommand.java	 \
  	DeleteCommand.java	 \
  	ExamineCommand.java	 \
  	ExpungeCommand.java	 \
  	FetchCommand.java	 \
  	IllegalStateCommand.java	 \
  	ListCommand.java	 \
  	LoginCommand.java	 \
  	LogoutCommand.java	 \
  	LsubCommand.java	 \
  	NoopCommand.java	 \
  	SelectCommand.java	 \
  	StatusCommand.java	 \
  	StoreCommand.java	 \
  	SubscribeCommand.java	 \
  	UnsubscribeCommand.java	

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

