PACKAGE = rice.testharness.messaging

SOURCE = \
 TestHarnessAddress.java \
 TestHarnessMessage.java \
 SubscribedMessage.java \
 UnsubscribedMessage.java \
 StartTestMessage.java \
 InitTestMessage.java \
 CollectResultsMessage.java \
 CollectResultsResponseMessage.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
