PACKAGE = rice.past

SOURCE  = \
	PAST.java \
	ContentHashPAST.java \
	SignedPAST.java \
	PASTContent.java\
	ContentHashPASTContent.java\
	PASTPolicy.java\
	SignedPASTContent.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
