PACKAGE = rice.past

SOURCE  = \
	PAST.java \
	PASTContent.java\
	PASTContentHandle.java\
	PASTException.java \
	ContentHashPASTContent.java\
	PASTService.java\
	PASTServiceImpl.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
