PACKAGE = rice.email

SOURCE  = \
	Email.java \
	Flags.java \
	EmailData.java \
	EmailDataReference.java \
	EmailService.java \
	Folder.java \
	StoredEmail.java \
  EmailContentPart.java \
  EmailMultiPart.java \
  EmailSinglePart.java \
  EmailMessagePart.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
