PACKAGE = rice.im.io

SOURCE  = \
  IMGui.java \
  IChatAction.java \
  ChatAction.java \
  BuddyFrame.java \
  BuddyPanel.java \
  BuddyTree.java \
  BuddyNode.java \
  UserFolderNode.java \
  UserNode.java \
  BuddyTreeCellRenderer.java \
  ChatFrame.java \
  ChatPanel.java \
  UserNodeAction.java \
  SwingWorker.java
  



RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
