PACKAGE = rice.p2p.replication.messaging

SOURCE  = \
	ReminderMessage.java\
	ReplicationMessage.java\
	RequestMessage.java\
	ResponseMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
