PACKAGE = rice.email.log

SOURCE  = \
	DeleteMailLogEntry.java \
	InsertMailLogEntry.java \
	DeleteFolderLogEntry.java \
	InsertFolderLogEntry.java \
	SnapShotLogEntry.java \
	DeleteMailEvent.java \
	InsertMailEvent.java \
	DeleteFolderEvent.java \
	InsertFolderEvent.java \
  EmailLog.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
