PACKAGE = rice.email.log

SOURCE  = \
	DeleteMailLogEntry.java \
	InsertMailLogEntry.java \
	SnapShotLogEntry.java \
	MailEvent.java \
	DeleteMailEvent.java \
	InsertMailEvent.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
