PACKAGE = rice.post.security.pknoi

SOURCE  = \
	PKnoIPostCertificate.java \
        PKnoISecurityModule.java \
	PKnoIChain.java \
	PKnoISignature.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


