PACKAGE = rice.ap3.routing

SOURCE  = \
	AP3RoutingTableEntryImpl.java \
	AP3RoutingTableEntry.java \
	AP3RoutingTableImpl.java \
	AP3RoutingTable.java \
	MessageIDCollisionException.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
