PACKAGE = rice.email.proxy

SOURCE  = \
  EmailProxy.java \
  CertificateAuthorityKeyGenerator.java \
  CertificateGenerator.java \
  password.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

