PACKAGE = rice.rm.messaging

SOURCE  = \
	RMMessage.java \
	RMReplicateMsg.java \
	RMReplicateResponseMsg.java \
	RMReplicateTimeoutMsg.java \
	RMInsertMsg.java \
	RMInsertResponseMsg.java \
	RMRequestKeysMsg.java \
	RMResponseKeysMsg.java
	#RMRemoveMsg.java \
	#RMDeleteMsg.java \



RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


