PACKAGE = rice.rm.messaging

SOURCE  = \
	RMMessage.java \
	RMRequestKeysMsg.java \
	RMResponseKeysMsg.java \
	RMMaintenanceMsg.java


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


