PACKAGE = rice.testharness.tests

SOURCE  = \
	LeafSetTest.java \
	TraceTest.java \
	PingTest.java \
  SplitStreamTest.java \
  Pinger.java \
  PastryPinger.java\
  PostTest.java\
  LogInsertPostTest.java\
  ContentHashInsertPostTest.java\
  ContentHashFetchPostTest.java\
  SignedInsertPostTest.java\
  PastTest.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
