PACKAGE = rice.pastry.testing

SOURCE  = \
	NodeIdUnit.java\
	DummyNodeHandle.java\
	RoutingTableUnit.java\
	PastryTest.java\
	PastryRegrTest.java\
	RegrTestApp.java


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
