PACKAGE = rice.scribe.messaging

SOURCE  = \
	MessageCreate.java \
	MessageHeartBeat.java \
	MessagePublish.java \
	MessageSubscribe.java \
	MessageUnsubscribe.java \
	ScribeMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
