PACKAGE = rice.scribe.testing

SOURCE  = \
	ScribeInteractiveTest.java \
	BasicScribeRegrTest.java \
	BasicScribeRegrTestApp.java \
	ScribeRegrTest.java \
	MRTracker.java \
	CSPair.java \
	ScribeMaintenanceTestApp.java \
	DirectScribeMaintenanceTest.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
