PACKAGE = rice.scribe.testing

SOURCE  = \
	BasicScribeRegrTest.java \
	BasicScribeRegrTestApp.java \
	MRTracker.java \
	CSPair.java \
	DirectScribeMaintenanceTestApp.java \
	DirectScribeMaintenanceTest.java \
	DirectScribeRegrTest.java \
	DistTopicLog.java\
	DistScribeRegrTestApp.java \
	DistScribeRegrTest.java\
	DistScribeRegrTestMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile





