PACKAGE = rice.scribe.testing

SOURCE  = \
	ScribeInteractiveTest.java \
	ScribeRegrTest.java \
	ScribeRegrTestApp.java \
	MRTracker.java \
	CSPair.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
