#***************************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#***************************************************************************

PACKAGES = \
	rice.pastry\
	rice.pastry.messaging\
	rice.pastry.routing\
	rice.pastry.leafset\
	rice.pastry.client\
	rice.pastry.join\
	rice.pastry.direct\
	rice.pastry.standard\
	rice.pastry.rmi\
	rice.pastry.testing\
	rice.scribe\
	rice.scribe.maintenance\
	rice.scribe.messaging\
	rice.scribe.security\
	rice.scribe.testing


NODOC_PACKAGES = 

JARS = pastry.jar

JARS_3RDPARTY = 

MAIN_CLASS     = PastryTest
MAIN_PACKAGE   = rice.pastry.testing

MAIN_JAR       = 


RUN_PARAMETERS = 


#***************************************************************************
#
# Javadoc
#
#***************************************************************************

WINDOWTITLE = 'Rice Pastry - API Specification'
DOCTITLE    = 'Rice Pastry API'
HEADER      = 'Rice Pastry API'
BOTTOM      = '<font size="-1">Copyright &copy; 2001 - Rice Pastry</font>'


include $(JAVA_DEV_ROOT)/make/Makefile
