PACKAGE = rice.email.proxy.smtp

SOURCE  = \
  SmtpConnection.java \
  SmtpHandler.java \
  SmtpServer.java \
  SmtpServerImpl.java \
  SmtpState.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
