PACKAGE = rice.pastry

SOURCE  = \
	Id.java\
	IdSet.java \
	IdRange.java \
	NodeId.java\
	NodeIdFactory.java\
	NodeHandle.java\
	LocalNode.java\
	LocalNodeI.java\
	PendingLocalNodesList.java\
	PastryNode.java\
	PastryNodeFactory.java\
	NodeSet.java\
	NodeSetUpdate.java \
	Log.java \
	PastrySeed.java\
	ScheduledMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
