PACKAGE = rice.p2p.scribe.messaging

SOURCE  = \
	ScribeMessage.java \
	AnycastMessage.java \
	DropMessage.java\
	PublishMessage.java \
	PublishRequestMessage.java \
	SubscribeMessage.java \
	SubscribeAckMessage.java \
	UnsubscribeMessage.java \
 	AbstractSubscribeMessage.java \
	SubscribeLostMessage.java \
	SubscribeFailedMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
