PACKAGE = rice.p2p.past

SOURCE  = \
	Past.java \
	PastImpl.java \
	PastContent.java\
	PastContentHandle.java\
	PastException.java \
	ContentHashPastContent.java \
	ContentHashPastContentHandle.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
