PACKAGE = rice.pastry.leafset

SOURCE  = \
	SimilarSet.java\
	LeafSet.java\
	RequestLeafSet.java\
	BroadcastLeafSet.java\
	LeafSetProtocolAddress.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
