PACKAGE = rice.post.security

SOURCE  = \
	PostCertificate.java \
	SecurityModule.java \
	SecurityService.java \
  SecurityUtils.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


