PACKAGE = rice.pastry.messaging

SOURCE  = \
	Address.java\
	Credentials.java\
	Message.java\
	MessageDispatch.java\
	MessageReceiver.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
