PACKAGE = rice.p2p.scribe

SOURCE  = \
	Scribe.java \
	ScribeImpl.java \
	ScribeContent.java \
	ScribeClient.java \
  ScribePolicy.java \
  Topic.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
