PACKAGE = rice.email.log

SOURCE  = \
	DeleteMailLogEntry.java \
	InsertMailLogEntry.java \
	SnapShotLogEntry.java \
	MoveMailLogEntry.java \
	CreateFolderLogEntry.java \
	DeleteFolderLogEntry.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
