PACKAGE = rice.post.messaging

SOURCE  = \
	NotificationMessage.java \
	EncryptedNotificationMessage.java \
	GroupNotificationMessage.java \
	PresenceMessage.java \
	ReceiptMessage.java \
	DeliveryRequestMessage.java \
	DeliveryLookupMessage.java \
	DeliveryLookupResponseMessage.java \
	DeliveryMessage.java \
	PostMessage.java \
	SignedPostMessage.java \
	SignedPostMessageWrapper.java \
	PostPastryMessage.java \
	PostScribeMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
