PACKAGE = rice.post.messaging

SOURCE  = \
	PostAddress.java \
	NotificationMessage.java \
	PresenceMessage.java \
	ReceiptMessage.java \
	DeliveryRequestMessage.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
