PACKAGE = rice.ap3.testing

SOURCE  = \
	AP3TestingClient.java \
	AP3Test.java \
	AP3TestingService.java \
	AP3TestingMessage.java \
	RMIAP3Test.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
