PACKAGE = rice.email

SOURCE  = \
	Email.java \
	EmailUserAddress.java \
	EmailAttachment.java \
	EmailBody.java \
	EmailService.java \
	EmailServiceListener.java \
	EmailGroupAddress.java \
	Folder.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
