PACKAGE = rice.ap3.messaging

SOURCE  = \
	AP3Address.java \
	AP3MessageIDImpl.java \
	AP3MessageID.java \
	AP3Message.java \
	AP3MessageType.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
