PACKAGE = rice.serialization

SOURCE  = \
	XMLObjectInputStream.java \
	XMLObjectOutputStream.java \
	XMLReader.java \
	XMLWriter.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
