PACKAGE = rice.email.log

SOURCE  = \
	DeleteMailLogEntry.java \
	InsertMailLogEntry.java \
	SnapShotLogEntry.java \
	UpdateMailLogEntry.java \
  EmailLog.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
