PACKAGE = rice.email.proxy.imap.parser.antlr

SOURCE  = \
  CommonLexTokenTypes.java \
  ImapCommandLexer.java \
  ImapCommandParser.java \
  ImapCommandParserTokenTypes.java \
  ImapLineParser.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

