PACKAGE = rice.past.search

SOURCE  = \
	IndexEntry.java \
	IndexKey.java \
	IndexKeyString.java \
	Searchable.java \
	SearchService.java \
	SearchServiceImpl.java \
	SearchTest.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
