PACKAGE = rice.pastry.multiring

SOURCE	= \
	MultiRingPastryNode.java\
	MultiRingPastryNodeFactory.java\
  MultiRingAppl.java\
  RingId.java\
  RingNodeId.java

MAIN	= 

include $(JAVA_DEV_ROOT)/Makefile
