PACKAGE = rice.pastry.socket.exception

SOURCE  = \
	SerializationException.java \
	DeserializationException.java \
	ImproperlyFormattedMessageException.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
