PACKAGE = rice.persistence

SOURCE  = \
  Catalog.java \
	Storage.java \
  MemoryStorage.java \
  PersistentStorage.java \
  Cache.java \
  LRUCache.java \
  StorageManager.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
