PACKAGE = rice.pastry.wire.messaging.socket

SOURCE  = \
	SocketMessage.java\
	SocketCommandMessage.java\
	SocketTransportMessage.java\
 	DisconnectMessage.java\
	HelloMessage.java\
	HelloResponseMessage.java\
	NodeIdRequestMessage.java\
	NodeIdResponseMessage.java\
	LeafSetRequestMessage.java\
	LeafSetResponseMessage.java\
	RouteRowRequestMessage.java\
	RouteRowResponseMessage.java\
  

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

