PACKAGE = rice.pastry.wire.messaging.socket

SOURCE  = \
	SocketMessage.java\
	SocketCommandMessage.java\
	SocketTransportMessage.java\
 	DisconnectMessage.java\
	HelloMessage.java\
	NodeIdRequestMessage.java\
	NodeIdResponseMessage.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

