PACKAGE = rice.splitstream.testing

SOURCE  = \
	BandwidthUnitTest.java \
	StripeUnitTest.java \
	ChannelUnitTest.java \
	SplitStreamUnitTest.java \
	DirectSplitStreamTest.java \
	DirectSplitStreamTestApp.java


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
