#***************************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#***************************************************************************

PACKAGES = \
	rice.pastry\
	rice.pastry.routing\
	rice.pastry.messaging
#	rice.pastry.network
#	rice.pastry.client\
#	rice.pastry.networkprototype\
#	rice.pastry.testclient\
#	rice.pastry.testing\
#	rice.pastry.testsocket\


NODOC_PACKAGES = 

JARS = 

JARS_3RDPARTY = 

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = 


RUN_PARAMETERS = 


#***************************************************************************
#
# Javadoc
#
#***************************************************************************

WINDOWTITLE = 'Rice Pastry - API Specification'
DOCTITLE    = 'Rice Pastry API'
HEADER      = 'Rice Pastry API'
BOTTOM      = '<font size="-1">Copyright &copy; 2001 - Rice Pastry</font>'


include $(JAVA_DEV_ROOT)/make/Makefile