#***************************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#***************************************************************************

# Note:
#  The "past" and "storage" packages require ObjectWeb.
#  Instructions for setting the OBJECTWEB_DIR environment
#  variable can be found in README.ObjectWeb.

PACKAGES = \
	rice.pastry\
	rice.pastry.messaging\
	rice.pastry.routing\
	rice.pastry.leafset\
	rice.pastry.client\
	rice.pastry.join\
	rice.pastry.direct\
	rice.pastry.standard\
	rice.pastry.rmi\
	rice.pastry.security\
	rice.pastry.testing\
	rice.scribe\
	rice.scribe.maintenance\
	rice.scribe.messaging\
	rice.scribe.security\
	rice.scribe.testing
#	rice.ap3\
#	rice.ap3.routing\
#	rice.ap3.messaging\
#	rice.ap3.testing\
#	rice.storage\
#	rice.storage.testing\
#	rice.past\
#	rice.past.messaging\
#	rice.past.testing\
#	rice.past.search\
#	rice.past.search.testing

NODOC_PACKAGES = 

JARS = pastry.jar

JARS_3RDPARTY = 

MAIN_CLASS     = PastryTest
MAIN_PACKAGE   = rice.pastry.testing

MAIN_JAR       = 


RUN_PARAMETERS = 


#***************************************************************************
#
# Javadoc
#
#***************************************************************************

WINDOWTITLE = 'Rice Pastry - API Specification'
DOCTITLE    = 'Rice Pastry API'
HEADER      = 'Rice Pastry API'
BOTTOM      = '<font size="-1">Copyright &copy; 2001 - Rice Pastry</font>'


include $(JAVA_DEV_ROOT)/make/Makefile

