#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#***************************************************************************

# Note:
#  The "storage" package requires ObjectWeb.
#  Instructions for setting the OBJECTWEB_DIR environment
#  variable can be found in README.ObjectWeb.

PACKAGES = \
	rice.pastry\
	rice.pastry.messaging\
	rice.pastry.routing\
	rice.pastry.leafset\
	rice.pastry.client\
	rice.pastry.join\
	rice.pastry.direct\
	rice.pastry.dist\
	rice.pastry.multiring\
	rice.pastry.multiring.messaging\
	rice.pastry.multiring.testing\
	rice.pastry.rmi\
	rice.pastry.standard\
	rice.pastry.security\
	rice.pastry.testing\
	rice.pastry.wire\
	rice.pastry.wire.exception\
	rice.pastry.wire.messaging.datagram\
	rice.pastry.wire.messaging.socket\
	rice.scribe\
	rice.scribe.maintenance\
	rice.scribe.messaging\
	rice.scribe.security\
	rice.scribe.testing\
	rice.splitstream\
	rice.splitstream.messaging\
	rice.splitstream.testing\
	rice.past\
	rice.past.messaging\
	rice.past.testing\
	rice.persistence\
	rice.persistence.testing\
	rice.rm\
	rice.rm.messaging\
	rice.rm.testing\
	rice.post\
	rice.post.log\
	rice.post.messaging\
	rice.post.storage\
	rice.post.testing\
	rice.email\
	rice.email.log\
	rice.email.messaging\
	rice.email.test\
	rice.email.proxy\
	rice.email.proxy.imap\
	rice.email.proxy.imap.commands\
	rice.email.proxy.imap.commands.fetch\
	rice.email.proxy.imap.parser.antlr\
	rice.email.proxy.mail\
	rice.email.proxy.mailbox\
	rice.email.proxy.mailbox.postbox\
	rice.email.proxy.smtp\
	rice.email.proxy.smtp.manager\
	rice.email.proxy.smtp.commands\
	rice.email.proxy.user 
#	rice.storage\
#	rice.storage.testing\
#	rice.past.search\
#	rice.past.search.testing
#	rice.ap3\
#	rice.ap3.routing\
#	rice.ap3.messaging\
#	rice.ap3.testing\

NODOC_PACKAGES = 

JARS = pastry.jar

JARS_LIB       = javamail.jar bouncycastle.jar antlr.jar

JARS_3RDPARTY = 

MAIN_CLASS     = PastryTest
MAIN_PACKAGE   = rice.pastry.testing

MAIN_JAR       = 

RUN_PARAMETERS = 


#***************************************************************************
#
# Javadoc
#
#***************************************************************************

WINDOWTITLE = 'Rice Pastry - API Specification'
DOCTITLE    = 'Rice Pastry API'
HEADER      = 'Rice Pastry API'
BOTTOM      = '<font size="-1">Copyright &copy; 2001 - Rice Pastry</font>'


include $(JAVA_DEV_ROOT)/make/Makefile


