PACKAGE = rice.email.proxy.imap.commands.fetch

SOURCE  = \
  BodyPart.java \
  BodyPartRequest.java \
  FetchOptionRegistry.java \
  FetchPart.java \
  MessagePropertyPart.java \
  NilPart.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

