PACKAGE = rice.past.messaging

SOURCE  = \
	PASTAddress.java\
	PASTMessageID.java\
	PASTMessageIDImpl.java\
	PASTMessage.java\
	MessageInsert.java\
	MessageLookup.java\
	MessageExists.java\
  MessageReclaim.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
