#***************************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#***************************************************************************

PACKAGES = \
	rice.util\
	rice.util.testing\
	rice.pastry\
	rice.pastry.messaging\
	rice.pastry.routing\
	rice.pastry.control\
	rice.pastry.client\
	rice.pastry.testing

NODOC_PACKAGES = 

JARS = 

JARS_3RDPARTY = 

MAIN_CLASS     = RoutingTableUnit
MAIN_PACKAGE   = rice.pastry.testing

MAIN_JAR       = 


RUN_PARAMETERS = 


#***************************************************************************
#
# Javadoc
#
#***************************************************************************

WINDOWTITLE = 'Rice Pastry - API Specification'
DOCTITLE    = 'Rice Pastry API'
HEADER      = 'Rice Pastry API'
BOTTOM      = '<font size="-1">Copyright &copy; 2001 - Rice Pastry</font>'


include $(JAVA_DEV_ROOT)/make/Makefile