PACKAGE = rice.pastry.socket.messaging

SOURCE  = \
	LeafSetRequestMessage.java\
	LeafSetResponseMessage.java \
	NodeIdRequestMessage.java \
	NodeIdResponseMessage.java\
	PingMessage.java\
	PingResponseMessage.java\
	RouteRowRequestMessage.java\
	RouteRowResponseMessage.java\
	SocketMessage.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
