PACKAGE = rice.email.proxy.imap.commands.search

SOURCE  = \
  SearchPart.java \
  AndSearchPart.java \
  DateArgSearchPart.java \
  HeaderSearchPart.java \
  NoArgSearchPart.java \
  NotSearchPart.java \
  NumberArgSearchPart.java \
  OrSearchPart.java \
  StringArgSearchPart.java \
  UIDSearchPart.java
  
RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

