#!/bin/bash
# build the hosts configuration directory with the actual IP addresses
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: build-hostconfig,v 1.3 2005/02/08 10:40:48 as Exp $

DIR=`dirname $0`

source $DIR/function.sh

[ -f $DIR/../testing.conf ] || die "!! Configuration file 'testing.conf' not found"
[ -d $DIR/../hosts ]        || die "!! Directory 'hosts' not found"

source $DIR/../testing.conf

if [ ! -d $BUILDDIR ]
then
    cecho " * Creating directory '$BUILDDIR'"
    mkdir $BUILDDIR
fi

########################################
# copy default host configs to $BUILDDIR
#

HOSTCONFIGDIR=${BUILDDIR}/hosts

if [ -d $HOSTCONFIGDIR ]
then
    rm -r $HOSTCONFIGDIR
fi

mkdir $HOSTCONFIGDIR
cp -rfp ${UMLTESTDIR}/testing/hosts $BUILDDIR

cecho " * Copied default host config directory to '$HOSTCONFIGDIR'"

########################################
# assign IP for each host to hostname
#

cecho-n " * Generate default config for.."

HOSTIP=`ifconfig eth0 |grep inet |sed -e "s/.*inet addr://" -e "s/  Bcast.*//"`

for host in $STRONGSWANHOSTS
do
    cecho-n "${host}.."
    eval ip_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $1 }' | awk '{ print $1 }'`"

    [ "`eval echo \\\$ip_${host}`" != "$HOSTIP" ] || die "$host has the same IP as eth0 (Host)! Please change that."

    case $host in
    mars)
        eval ip1_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $2 }' | awk '{ print $1 }'`"
        [ "`eval echo \\\$ip1_${host}`" != "$HOSTIP" ] || die "eth1 of $host has the same IP as eth0 (Host)! Please change that."
        searchandreplace PH_IP_MARS $ip_mars $HOSTCONFIGDIR
        searchandreplace PH_IP1_MARS $ip1_mars $HOSTCONFIGDIR
        ;;
    venus)
        eval ip1_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $2 }' | awk '{ print $1 }'`"
	[ "`eval echo \\\$ip1_${host}`" != "$HOSTIP" ] || die "eth1 of $host has the same IP as eth0 (Host)! Please change that."
	searchandreplace PH_IP_VENUS $ip_venus $HOSTCONFIGDIR
	searchandreplace PH_IP1_VENUS $ip1_venus $HOSTCONFIGDIR
	;;
    jupiter)
        eval ip1_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $2 }' | awk '{ print $1 }'`"
        [ "`eval echo \\\$ip1_${host}`" != "$HOSTIP" ] || die "eth1 of $host has the same IP as eth0 (Host)! Please change that."
        searchandreplace PH_IP_JUPITER $ip_jupiter $HOSTCONFIGDIR
        searchandreplace PH_IP1_JUPITER $ip1_jupiter $HOSTCONFIGDIR
        ;;
    alice)
        searchandreplace PH_IP_ALICE $ip_alice $HOSTCONFIGDIR
        ;;
    bob)
        searchandreplace PH_IP_BOB $ip_bob $HOSTCONFIGDIR
        ;;
    carol)
        searchandreplace PH_IP_CAROL $ip_carol $HOSTCONFIGDIR
	;;
    dave)
        searchandreplace PH_IP_DAVE $ip_dave $HOSTCONFIGDIR
        ;;
    eve)
        searchandreplace PH_IP_EVE $ip_eve $HOSTCONFIGDIR
        ;;
    fred)
        searchandreplace PH_IP_FRED $ip_fred $HOSTCONFIGDIR
        ;;
    grace)
        eval ip1_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $2 }' | awk '{ print $1 }'`"
        searchandreplace PH_IP_GRACE $ip_grace $HOSTCONFIGDIR
        searchandreplace PH_IP1_GRACE $ip1_grace $HOSTCONFIGDIR
        ;;
    harold)
        eval ip1_${host}="`echo $HOSTNAMEIPS | sed -n -e "s/^.*${host}://gp" | awk -F : '{ print $2 }' | awk '{ print $1 }'`"
        searchandreplace PH_IP_HAROLD $ip_harold $HOSTCONFIGDIR
        searchandreplace PH_IP1_HAROLD $ip1_harold $HOSTCONFIGDIR
        ;;
    esac
done

cecho "done"
