PACKAGE = rice.scribe.maintenance

SOURCE  = \
	HeartBeatEvent.java \
	MaintenanceEvent.java \
	ScribeScheduler.java \
	TreeRepairEvent.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
