#!/bin/sh

if [ ! -f epost.jar ]; then
	echo "error: must be run from the epost-cert-server directory"
	exit 1
fi

JAVA=`which java`

PORT=9665

LOCALHOST=`hostname`

if [ -z "$JAVA" ]; then
	JAVA=/usr/java/j2sdk1.4.2_05/bin/java
fi

if [ ! -f "$JAVA" ]; then
	echo "error: couldn't find java"
	exit 1
fi

case $1 in
	start)
		$JAVA -cp epost.jar:mysql-connector.jar rice.certgenerator.CertificateServer \
			$PORT \
			> server.$LOCALHOST.out 2>&1 &
		disown %1
		pid=`ps ax | grep 'java.*Cert' | grep -v grep | cut -f1 -d' '`
		echo $pid > server.$LOCALHOST.pid
		echo "server pid is $pid"
		;;
	stop)
		pid=`ps ax | grep 'java.*Cert' | grep -v grep | cut -f1 -d' '`
		if [ ! -z "$pid" ]; then
			echo "killing: $pid"
			kill $pid > /dev/null 2>&1
			sleep 3
			kill -9 $pid > /dev/null 2>&1
		else
			echo "server not running"
		fi
		;;
	*)
		echo "usage: $0 (start|stop)"
		;;
esac