PACKAGE = rice.post.security.ca

SOURCE  = \
	CAPostCertificate.java \
  CAKeyGenerator.java \
  CACertificateGenerator.java \
  CASecurityModule.java \
  password.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


