PACKAGE = rice.pastry.testing

SOURCE  = \
	HelloWorld.java RMIHelloWorld.java HelloWorldApp.java \
	\
	PastryTest.java RMIPastryTest.java PingClient.java\
	\
	PastryRegrTest.java DirectPastryRegrTest.java RMIPastryRegrTest.java\
	RegrTestApp.java\
	\
	NodeIdUnit.java\
	PingMessage.java PingAddress.java Ping.java PingTestNew.java SinglePingTest.java\
	PingTestRecord.java


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
