PACKAGE = rice.pastry.testing

SOURCE  = \
	HelloWorld.java \
	HelloWorldApp.java \
	PastryTest.java \
	PingClient.java\
	PastryRegrTest.java \
	DirectPastryRegrTest.java \
	DistPastryRegrTest.java \
	DistHelloWorld.java \
	RegrTestApp.java\
	NodeIdUnit.java\
	IdRangeUnit.java\
	PingMessage.java \
	PingMessageNew.java \
	PingAddress.java \
	Ping.java \
	SinglePingTest.java \
	PingTestRecord.java \
	DirectPastryPingTest.java \
  LeafSetTest.java


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
