PACKAGE = rice.p2p.splitstream

SOURCE  = \
	Channel.java \
	ChannelId.java \
	SplitStreamImpl.java \
	SplitStream.java \
	SplitStreamClient.java \
	SplitStreamContent.java \
	SplitStreamScribePolicy.java \
	SplitStreamSubscribeContent.java \
	Stripe.java \
	StripeId.java 



RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
