PACKAGE = rice.email.proxy.smtp.commands

SOURCE  = \
  DataCommand.java \
  HeloCommand.java \
  MailCommand.java \
  NoopCommand.java \
  QuitCommand.java \
  RcptCommand.java \
  RsetCommand.java \
  SmtpCommand.java \
  SmtpCommandRegistry.java \
  VrfyCommand.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
