PACKAGE = rice.past.search

SOURCE  = \
	Combinator.java \
	IndexEntry.java \
	IndexKeyString.java \
	IndexPlaceholder.java \
	Searchable.java \
	SearchService.java \
	SearchServiceImpl.java 

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
