PACKAGE = rice.pastry.direct

SOURCE  = \
	DirectPastryNode.java\
	DirectNodeHandle.java\
	NetworkSimulator.java\
	DirectSecurityManager.java\
	DirectPastryNodeFactory.java\
	EuclideanNetwork.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
