PACKAGE = rice.rm.testing

SOURCE  = \
	DirectRMRegrTestApp.java \
	DirectRMRegrTest.java \
	RMRegrTestApp.java \
	TestMessage.java \
	HeartbeatMsg.java \
	RefreshMsg.java \
	ReplicateMsg.java \
	ReplicateResponseMsg.java \
	ReplicateTimeoutMsg.java \
	InsertMsg.java \
	InsertResponseMsg.java \
	ObjectInsertionMsg.java \
	ObjectRefreshMsg.java \
	InvariantCheckMsg.java \
	DistRMRegrTest.java \
	DistRMRegrTestApp.java 
	#ObjectState.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile