PACKAGE = rice.rm.testing

SOURCE  = \
	DirectRMRegrTestApp.java \
	DirectRMRegrTest.java \
	DistRMRegrTest.java \
	DistRMRegrTestApp.java \
	DistRMRegrTestMessage.java \
	DistRMRegrTestReplicateMessage.java \
	ObjectState.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile