PACKAGE = rice.pastry.wire.messaging.datagram

SOURCE  = \
	PingMessage.java\
	PingResponseMessage.java\
	AcknowledgementMessage.java\
	DatagramMessage.java\
	DatagramTransportMessage.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

