PACKAGE = rice.pastry.security

SOURCE  = \
	Credentials.java\
	PastrySecurityManager.java\
	PermissiveCredentials.java\
	PermissiveSecurityManager.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
