PACKAGE = rice.testharness

SOURCE  = \
 TestHarness.java \
 DistTestHarnessRunner.java \
 MultiRingDistTestHarnessRunner.java \
 MultiRingTestHarness.java\
 Test.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
