PACKAGE = rice.email.proxy.mailbox

SOURCE  = \
  FlagList.java \
  Mailbox.java \
  MailboxException.java \
  MailboxManager.java \
  MailFolder.java \
  MsgFilter.java \
  MsgRangeFilter.java \
  MsgSetFilter.java \
  NoSuchMailboxException.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
