PACKAGE = rice.pastry

SOURCE  = \
	NodeId.java\
	NodeIdFactory.java\
	PastryNode.java\
	PastryNodeFactory.java\
	SecurityManager.java\
	RoutingManager.java\
	SimilarityComparator.java\
	ProximityComparator.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
