PACKAGE = rice.scribe

SOURCE  = \
	TestPastry.java \
	TestPastryApp.java \
	IScribe.java \
	IScribeApp.java \
	Scribe.java \
	Topic.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
