PACKAGE = rice.pastry.wire.testing

SOURCE  = \
	HelloMessageDigest.java\
	MessageDigest.java\
	MessageDigestFactory.java\
	PublishMessageDigest.java\
	WireFileFilter.java\
	WireFileProcessor.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
