PACKAGE = rice.pastry.wire.testing

SOURCE  = \
	HelloMessageDigest.java\
	MessageDigest.java
	MessageDigestFactory.java
	PublishMessageDigest.java
	WireFIleFilter.java
	WireFIleProcessor.java

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
