PACKAGE = rice.email.proxy.imap

SOURCE  = \
  ImapConnection.java \
  ImapServer.java \
  ImapServerImpl.java \
  ImapState.java \
  ParserImapHandler.java \
  Quittable.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile

