PACKAGE = rice.scribe.messaging

SOURCE  = \
	MessageCreate.java \
	MessageHeartBeat.java \
	MessagePublish.java \
	MessageSubscribe.java \
	MessageUnsubscribe.java \
	MessageAckOnSubscribe.java \
	MessageRequestToParent.java \
	MessageReplyFromParent.java \
	ScribeMessage.java 


RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
