PACKAGE = rice.post.security

SOURCE  = \
	SecurityService.java \
	PostSignature.java \
	PostCertificate.java \
  CertificateAuthorityKeyGenerator.java \
  CertificateGenerator.java \
  password.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile


