PACKAGE = rice.email.proxy.user

SOURCE  = \
  NoSuchUserException.java \
  User.java \
  UserException.java \
  UserImpl.java \
  UserManager.java \
  UserManagerImpl.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
