PACKAGE = rice.post.storage

SOURCE  = \
	PostData.java \
	StorageService.java \
	ContentHashData.java \
	ContentHashReference.java \
	SignedData.java \
	SignedReference.java \
	SecureData.java \
	SecureReference.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
