PACKAGE = rice.pastry.standard

SOURCE  = \
	StandardRouter.java\
	RandomNodeIdFactory.java\
	StandardLeafSetProtocol.java\
	StandardRouteSetProtocol.java\
	StandardJoinProtocol.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
