PACKAGE = rice.persistence.testing

SOURCE  = \
  Test.java \
  MemoryStorageTest.java \
  PersistentStorageTest.java \
  LRUCacheTest.java

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
